server:
  port: 8082


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jervis.cn:13306/wdbs
    username: jadb
    password: gd.jervis
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: classpath:mapper/**.xml
  config-location: classpath:mybatis-config.xml
